version: '3.3'
services:
  nginx:
    image: ubergarm/openresty-nginx-jwt
    ports:
      - "80:80"
      - "443:443"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./nginx.conf:/nginx.conf:Z
      - ./bearer.lua:/bearer.lua:Z
      - ./mixes:/www:Z
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  webhook:
    image: dr33m/webhook
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - DR33M_ADMIN_ID=${DR33M_ADMIN_ID}
      - DR33M_SECRET=${JWT_SECRET}

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
